/**
 * Template: tech-minimal (科技简约) — render.js
 *
 * Dark surface + cyan accent. Charts use a dark theme (transparent background,
 * cyan/blue palette).
 */
(function () {
  "use strict";

  var THEME = {
    palette: ["#00d4a4", "#4f8cff", "#a473ff", "#ffb547", "#ff6b6b", "#3ad6c5"],
    textColor: "#e6eaf2",
    axisColor: "#8794a8",
    splitColor: "#232b39",
    fontFamily: '"JetBrains Mono", "PingFang SC", "SF Mono", monospace'
  };

  function renderReport(data, container, ctx) {
    var meta = (data && data.meta) || {};
    var sections = (data && data.sections) || [];

    var header = h(container, "div", "rf-doc-header");
    h(header, "div", "rf-eyebrow", "▌ " + (meta.date || "REPORT") + " · v" + (meta.version || "1"));
    h(header, "h1", "rf-doc-title", meta.title || "未命名报告");
    if (meta.subtitle) h(header, "div", "rf-doc-subtitle", meta.subtitle);

    var byline = h(header, "div", "rf-doc-byline");
    if (meta.author) h(byline, "span", "", "author: " + meta.author);
    if (meta.date)   h(byline, "span", "", "date: "   + meta.date);

    if (Array.isArray(meta.tags) && meta.tags.length) {
      var tagsBox = h(header, "div", "rf-tags");
      meta.tags.forEach(function (t) { h(tagsBox, "span", "rf-tag", "#" + t); });
    }

    sections.forEach(function (sec, idx) {
      var secEl = h(container, "section", "rf-section");
      h(secEl, "h2", "rf-section__heading", sec.heading || "");
      (sec.blocks || []).forEach(function (blk) { renderBlock(blk, secEl, ctx); });
    });

    h(container, "div", "rf-doc-footer",
      "[ END OF REPORT // generated by reportflow @ " + new Date().toISOString().split("T")[0] + " ]");
  }

  function renderBlock(blk, host, ctx) {
    if (!blk || !blk.type) return;
    var wrap = h(host, "div", "rf-block rf-block--" + blk.type);

    if (blk.type === "text") {
      var html = blk.format === "plain"
        ? "<p>" + ctx.escapeHtml(blk.content || "").replace(/\n/g, "<br>") + "</p>"
        : ctx.marked(blk.content || "");
      var box = h(wrap, "div", "rf-text"); box.innerHTML = html;
      return;
    }
    if (blk.type === "chart") {
      var card = h(wrap, "div", "rf-chart-card");
      if (blk.title) h(card, "div", "rf-chart-card__title", "// " + blk.title);
      var body = h(card, "div", "rf-chart-card__body");
      requestAnimationFrame(function () {
        try { ctx.renderChart(blk.spec, body, THEME); }
        catch (e) { body.textContent = "图表渲染失败"; }
      });
      return;
    }
    if (blk.type === "image") {
      var fig = h(wrap, "figure", "rf-img");
      var img = h(fig, "img"); img.alt = blk.caption || "";
      if (blk.assetId) {
        Promise.resolve(ctx.resolveAssetUrl(blk.assetId)).then(function (url) {
          if (url) img.src = url;
        });
        img.setAttribute("data-rf-asset", blk.assetId);
      } else if (blk.src) {
        img.src = blk.src;
      }
      if (blk.caption) h(fig, "figcaption", "rf-img__caption", "fig: " + blk.caption);
    }
  }

  function h(parent, tag, cls, text) {
    var el = (parent.ownerDocument || document).createElement(tag);
    if (cls) el.className = cls;
    if (text != null) el.textContent = text;
    parent.appendChild(el);
    return el;
  }

  window.ReportFlowTemplates.register({
    manifest: {
      id: "tech-minimal",
      name: "科技简约",
      version: "1.0.0",
      author: "ReportFlow",
      description: "深色背景 + 青绿强调，适合数据驱动的技术汇报。",
      stylesheet: "style.css",
      capabilities: { charts: ["pie", "bar", "line"], images: true, pdfSafe: false }
    },
    theme: THEME,
    renderReport: renderReport
  });
})();
