/**
 * Template: minimal-business (极简商务) — render.js
 */
(function () {
  "use strict";

  var THEME = {
    palette: ["#d4a64a", "#222222", "#9aa0aa", "#cbd5e1", "#5b8def", "#1f7a4d"],
    textColor: "#222",
    axisColor: "#9aa0aa",
    splitColor: "#eee",
    fontFamily: '"PingFang SC", "Helvetica Neue", sans-serif'
  };

  function renderReport(data, container, ctx) {
    var meta = (data && data.meta) || {};
    var sections = (data && data.sections) || [];

    var header = h(container, "div", "rf-doc-header");
    h(header, "div", "rf-eyebrow", meta.date ? "REPORT · " + meta.date : "REPORT");
    h(header, "h1", "rf-doc-title", meta.title || "未命名报告");
    if (meta.subtitle) h(header, "div", "rf-doc-subtitle", meta.subtitle);

    var byline = h(header, "div", "rf-doc-byline");
    if (meta.author) {
      var s1 = h(byline, "span");
      h(s1, "span", "rf-key", "AUTHOR");
      h(s1, "span", "", meta.author);
    }
    if (meta.date) {
      var s2 = h(byline, "span");
      h(s2, "span", "rf-key", "DATE");
      h(s2, "span", "", meta.date);
    }

    if (Array.isArray(meta.tags) && meta.tags.length) {
      var tagsBox = h(header, "div", "rf-tags");
      meta.tags.forEach(function (t) { h(tagsBox, "span", "rf-tag", t); });
    }

    sections.forEach(function (sec) {
      var secEl = h(container, "section", "rf-section");
      h(secEl, "h2", "rf-section__heading", sec.heading || "");
      (sec.blocks || []).forEach(function (blk) { renderBlock(blk, secEl, ctx); });
    });

    h(container, "div", "rf-doc-footer", "GENERATED BY REPORTFLOW");
  }

  function renderBlock(blk, host, ctx) {
    if (!blk || !blk.type) return;
    var wrap = h(host, "div", "rf-block rf-block--" + blk.type);

    if (blk.type === "text") {
      var html = blk.format === "plain"
        ? "<p>" + ctx.escapeHtml(blk.content || "").replace(/\n/g, "<br>") + "</p>"
        : ctx.marked(blk.content || "");
      var box = h(wrap, "div", "rf-text"); box.innerHTML = html;
      return;
    }
    if (blk.type === "chart") {
      var card = h(wrap, "div", "rf-chart-card");
      if (blk.title) h(card, "div", "rf-chart-card__title", blk.title);
      var body = h(card, "div", "rf-chart-card__body");
      requestAnimationFrame(function () {
        try { ctx.renderChart(blk.spec, body, THEME); }
        catch (e) { body.textContent = "图表渲染失败"; }
      });
      return;
    }
    if (blk.type === "image") {
      var fig = h(wrap, "figure", "rf-img");
      var img = h(fig, "img"); img.alt = blk.caption || "";
      if (blk.assetId) {
        Promise.resolve(ctx.resolveAssetUrl(blk.assetId)).then(function (url) {
          if (url) img.src = url;
        });
        img.setAttribute("data-rf-asset", blk.assetId);
      } else if (blk.src) {
        img.src = blk.src;
      }
      if (blk.caption) h(fig, "figcaption", "rf-img__caption", blk.caption);
    }

    if (blk.type === "table") {
      if (window.RF_TableFormat && window.RF_TableFormat.renderTableHtml) {
        wrap.insertAdjacentHTML("beforeend", window.RF_TableFormat.renderTableHtml(blk, {
          figClass:   "rf-tpl-minimal-business-table",
          tableClass: "rf-table"
        }));
      } else {
        wrap.textContent = "（表格模块未加载）";
      }
    }
  }

  function h(parent, tag, cls, text) {
    var el = (parent.ownerDocument || document).createElement(tag);
    if (cls) el.className = cls;
    if (text != null) el.textContent = text;
    parent.appendChild(el);
    return el;
  }

  window.ReportFlowTemplates.register({
    manifest: {
      id: "minimal-business",
      name: "极简商务",
      version: "1.0.0",
      author: "ReportFlow",
      description: "灰白衬线 + 大留白 + 金色点缀，适合简洁的商务汇报。",
      stylesheet: "style.css",
      capabilities: { charts: ["pie", "bar", "line"], images: true, pdfSafe: true }
    },
    theme: THEME,
    renderReport: renderReport
  });
})();
